FROM alpine:3.20

RUN apk add --no-cache curl

WORKDIR /app

COPY scripts/run-duckdns-updater.sh /app/run-duckdns-updater.sh

RUN chmod +x /app/run-duckdns-updater.sh

ENTRYPOINT ["/app/run-duckdns-updater.sh"]
